# https://github.com/actions/javascript-action

name: 'Report LCOV'
description: 'Report code coverage from LCOV files'
author: 'Zennon Gosalvez'
inputs:
  coverage-files:
    description: 'The coverage files to scan. For example: `coverage/lcov.*.info`'
    required: true
  artifact-name:
    description: |
      The GitHub artifact name of the generated HTML report.
      Optional. Default: `` (Do not create a HTML report and do not upload anything.)
  minimum-coverage:
    description: 'The minimum coverage to pass the check. Optional. Default: `0` (always passes)'
    default: '0'
  github-token:
    description: |
      'Set the GitHub token to have the action comment the coverage summary in the pull request.
      This token is provided by Actions, you do not need to create your own token. Optional. Default: ``'
  working-directory:
    description: 'The working directory containing the source files referenced in the LCOV files. Optional. Default: `./`'
  additional-message:
    description: 'Custom text appended to the code coverage comment in the pull request. Optional. Default: ``'
    required: false
  update-comment:
    description: |
      Set to `true` to update the previous code coverage comment if such exists.
      When set to `false`, a new comment is always created. Optional. Default: `false`
    required: false
    default: 'false'
  list-full-paths:
    description: |
      Whether or not to list full paths for reported files
      Required: `false`
      Default: `true`
    required: false
    default: 'true'
outputs:
  total-coverage:
      description: 'The total coverage from scanned files.'

runs:
  using: 'node16'
  pre: 'dist/pre/index.js'
  pre-if: runner.os == 'linux' || runner.os == 'macOS'
  main: 'dist/main/index.js'
branding:
  icon: umbrella
  color: purple
