name: 'Report LCOV'
description: 'Report code coverage from LCOV files'
author: 'Zennon Gosalvez'
branding:
  icon: umbrella
  color: purple

inputs:
  coverage-files:
    description: Coverage files to scan (e.g. `coverage/lcov.*.info`).
    required: true
  artifact-name:
    description: Name of generated coverage report artifact. Default is no artifact created.
    required: false
  minimum-line-coverage:
    description: Minimum % line coverage to pass check. Default `0`.
    required: false
    default: '0'
  minimum-branch-coverage:
    description: Minimum % branch coverage to pass check. Default `0`.
    required: false
    default: '0'
  minimum-function-coverage:
    description: Minimum % function coverage to pass check. Default `0`.
    required: false
    default: '0'
  github-token:
    description: GitHub token to comment on PR.
    required: false
  working-directory:
    description: Directory containing source files. Default `./`
    required: false
    default: './'
  update-comment:
    description: Whether to update existing comment. Default `false`.
    required: false
    default: 'false'
outputs:
  total-line-coverage:
    description: Total line coverage.
  total-branch-coverage:
    description: Total branch coverage.
  total-function-coverage:
    description: Total function coverage.
  merged-lcov-file:
    description: Path to merged LCOV file.

runs:
  using: 'node16'
  pre: 'dist/pre.js'
  pre-if: runner.os == 'linux' || runner.os == 'macOS'
  main: 'dist/main.js'
